### ISSUE TITLE
Amethyst Load Macro Pointless Button

### ISSUE THREAD

**Issue by Scrooner13** [ninXout/Crystal-Client#12]
So i have a .mhr file works fine with any macro playback bot on windows and im on mac and i have the same .mhr file and no matter what whenever i click the load macro button, nothing happens, i even opened game files and put it in the section in amethyst where it says macros and still nothing.

**Comment by scrahe** [comment]
Does the .mhr format support names? You need a name to load a macro.

**Comment by scrahe** [comment]
Also, I don’t think the .mhr format works with other macro bots.

**Comment by scrahe** [comment]
Also, .mhr files might not work on Mac.

**Comment by ninXout** [comment]
oh my god do you realize that amethyst uses a custom macro format and that you cant just use megahack macros and expect it to work with my bot?
