### ISSUE TITLE
StartPOS switcher doesn't work.

### ISSUE THREAD

**Issue by hellonearth311** [ninXout/Crystal-Client#23]
I have tried to use the startPOS switcher many times (macOS sonoma by the way if you need that info). I press the arrow keys while the switcher is on the screen, and it does nothing. No startPOSes are swapped or anything.

**Comment by scrahe** [comment]
If you look at the shortcuts menu, at the bottom there is 2 dropdown menus and a button. For start pos switcher to work, you need to bind keys to it. To do this, choose the second dropdown to be Switcher Left, and choose the first dropdown to be the key bind you want. Then, do the same for Switcher Right.

**Comment by hellonearth311** [comment]
Ohhhhhh. Thank you very much! I'll close the issue now :)

> If you look at the shortcuts menu, at the bottom there is 2 dropdown menus and a button. For start pos switcher to work, you need to bind keys to it. To do this, choose the second dropdown to be Switcher Left, and choose the first dropdown to be the key bind you want. Then, do the same for Switcher Right.
