### ISSUE TITLE
Amethyst Clickbot crashes game

### ISSUE THREAD

**Issue by Omay238** [ninXout/Crystal-Client#3]
I'm aware that Amethyst is still in beta, although it is possible you didn't know about this bug, so just informing you.

**Comment by ninXout** [comment]
Clickbot adds fake click sounds to a macro completion, so a crash means that you do not have clicksounds in the correct place. Click sounds should be located at geode/config/ninxout.crystalclient/Amethyst/ClickBot. Thank you for your concern.
