### ISSUE TITLE
Broken in Geode v2

### ISSUE THREAD

**Issue by necocat0918** [ninXout/Crystal-Client#30]
it is not working in 2.2 :(

**Comment by scrahe** [comment]
Yes, 2.2 support is being developed.

**Comment by ghost** [comment]
@ninXout JUST BUILD THE 2.2 VERSION, I DON'T CARE IF IT IS DONE OR SOMETHING

**Comment by ghost** [comment]
He did check geode

**Comment by ghost** [comment]
wait what

**Comment by ghost** [comment]
NOT FOR WINDOWS!!!!!!
AND UNDOWNLOADABLE

Edit: Sorry I was wrong, but still, it is only on mac
